* 2020-07-08

  This version improves appareance of  gemini page rendering and fixed
  a bug in a command line switch.

* 2020-07-04

  Fixed some bugs in gemini viewer.
  Corrected expansion of retooted messages.

* 2020-06-29

  - improved  gemini navigation.   It  is  possible to  go  back in  a
    previous viewed address oe open an arbitrary URL.

* 2020-06-22

  - The software includes a gemini client

* 2020-06-13

  - Fixed bugs when fetching messages that made the program crashed.

* 2020-06-12

  - the downloading of messages should  be faster but now some threads
    do not get automatic expansions.  Thread messages expansion can be
    requested with a command, bound - by default- to "R".

* 2020-06-11
  - The software try to skips over statuses authored from an ignored user
  - in the configuration file the directive
    + ~ignore-user-regexp~  can be used  in the configuration  file to
      ignore users;  the value  of this variable  should be  a regular
      expression that  should matches the  username, if a  match occurs
      the user is ignored.


* 2020-06-07

  - version 0.0.4
    - Added polls voting;
    - added the possibility to force expanding of a message tree;
    - added  optional notification  of  statuses  mentioning the  user
      (--notify-mentions);
    - many bug fixed.

* 2020-05-18
  Added the reset of timeline pagination from command line.

* 2020-05-17
  Added a window to browse the links a status contains

* 2020-05-15
  Initial release
