* 2021-01-21 version 0.5.1

  - New features
    - [gemini] added support for favicon.txt more or less as specified in
      gemini://mozz.us/files/rfc_gemini_favicon.gmi
      (it does render the first character of the file instead of checking
      for emoji characters);
    - made the text for toot's visibility level (as rendered in main window)
      configurable.
    - Bugfix
      - fixed many problems in gemlog subscriptions;
      - fixed regression: using client certificate for gemini capsules
        works again;
      For other bugfix, please check the changelog.
    - Misc
      - removed dependency form libidn2.

* 2021-01-10 version 0.5.0

  - New features
    - added subscriptions to gemlog  according to the following gemini
      specification:
      gemini://gemini.circumlunar.space/docs/companion/subscription.gmi
    - Bugfix
      - Fixed configure scripts and several problems related to wrapping libidn2.
      - Building the  program from sources  should not fails  anymore on
        debian stable and *BSD.
      - it is possible  to use the program as a  gemini client without
        configure a connection with a pleroma server;

* 2020-12-31 version 0.4.2

 - Bugfix
   - Removed lag when scrolling the main window
 - New modules
   - Added a module to rewrite URLs in main and link windows.

* 2020-12-30 version 0.4.1

 - New features
  - allow repeat search on links window's items;
  - updated Italian translation;
  - added a command to send data to an external program.
 - Bugfix
   - fixed a  bug that  caused a redirect  loop when  accessing gemini
     pages with a  path components of URL that terminate  with a slash
     (e.g. ~.../foo/bar/~).

* 2020-12-29 version 0.4.0

  - New features
    - added a command to repeat the last performed search;
    - "new-line" (aka 'enter') key can be used to scroll main window;
    - [gemini] added a command to refresh a page;
  - Modules
    - added a module to share a gemini link on pleroma.
  - Scripts
    - added a simple script for a welcome bot.
  - Bugfix
    - fixed IRI parsing and encoding/normalizing;
    - fixed false positive for new message on subscribed tags;
    - [gemini] fixed bug that prevented visit the same link more than
      once;
    - fixed bugs that prevented following of users whit no messages in
      local database;
    - fixed ~quick_quicklisp.sh~ building script (thanks to Ben!).
  - Documentation
    - updated manpage.

* 2020-12-14 version 0.3.3

  This version switched from URI to IRI to resolve DNS names.

  This means  that users can uses  UTF-8 characters in host  name when
  resolving a gemini address.

* 2020-12-11

  This is  a bugfix release  that allows  tinmop to compile  and works
  with newer SBCL compiler.

  Also fixed  a problem  that made  the user stuck  if trying  to quit
  keeping messages marked for deletion.

* 2020-10-25

  Gemini browser got client authentication support.

* 2020-10-01

  Several improvements to the gemini browser added.

  Also a  bug that made the  program crash when getting  mentions from
  the server has been fixed.

  The command line switch "-m"  to get notification when mentioned did
  not works at all and has been fixed.

* 2020-09-19

  Added adding an optional mention when composing a message.
  Fixed a bug that made the message composition window to disappear
  before actually sending the message.

* 2020-09-12

  Added support for pleroma chat.
  Added managing of gemini streams. A gemini window allow to abort,
  rendering/opening of gemini connection while streaming.

* 2020-08-30

  Added a  window to manage all  the gemini streams opened.   The user
  can ispect the status o all the streams as well abort or open them.

* 2020-08-19

  The gemini  client could  now manage  secret input  if asked  by the
  server.

  Secret input here means that a placeholder character is printed on
  the  screen  instead of  the  character  corresponding to  the  key
  pressed by the user (like a password input).

* 2020-07-17

  The gemini client fetch documents from remote server in a concurrent
  way  now.  This way  streamed  contents  could be  accessed  without
  blocking the client.

* 2020-07-17

  Prevented  a crash  if an  invalid regular  expression is  used when
  searching in a message window.

* 2020-07-15

  This version fixes some bugs in gemini page rendering and add an
  option to display the source of a page.

* 2020-07-08

  This version improves appearance of  gemini page rendering and fixed
  a bug in a command line switch.

* 2020-07-04

  Fixed some bugs in gemini viewer.
  Corrected expansion of retooted messages.

* 2020-06-29

  - improved  gemini navigation.   It  is  possible to  go  back in  a
    previous viewed address or open an arbitrary URL.

* 2020-06-22

  - The software includes a gemini client

* 2020-06-13

  - Fixed bugs when fetching messages that made the program crashed.

* 2020-06-12

  - the downloading of messages should  be faster but now some threads
    do not get automatic expansions.  Thread messages expansion can be
    requested with a command, bound - by default- to "R".

* 2020-06-11
  - The software try to skips over statuses authored from an ignored user
  - in the configuration file the directive
    + ~ignore-user-regexp~  can be used  in the configuration  file to
      ignore users;  the value  of this variable  should be  a regular
      expression that  should matches the  username, if a  match occurs
      the user is ignored.


* 2020-06-07

  - version 0.0.4
    - Added polls voting;
    - added the possibility to force expanding of a message tree;
    - added  optional notification  of  statuses  mentioning the  user
      (--notify-mentions);
    - many bug fixed.

* 2020-05-18
  Added the reset of timeline pagination from command line.

* 2020-05-17
  Added a window to browse the links a status contains

* 2020-05-15
  Initial release
